  File "/home/user/Projects/dev_ws/install/pathfinding/lib/python3.8/site-packages/pathfinding/pathfinding_service.py", line 39
    for n in in self.graph:
             ^
SyntaxError: invalid syntax

